# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release - Tag and release package

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      # Ignore release candidates
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  node_version: 17.5
  pnpm_version: 6.32.0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup pnpm ${{ env.pnpm_version }}
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ env.pnpm_version }}

      - name: Setup Node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate Release changelog
        run: pnpx extract-changelog-release --yes > RELEASE.md

      - name: Push Release to github
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md
